# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: US Presidents
email: your-email@domain.com
description: >
  Data about all the US presidents in history.
baseurl: "/gitdash" # the subpath of your site, e.g. /blog
url: "http://alixedi.github.io" # the base hostname & protocol for your site
twitter_username: alixedi
github_username:  alixedi
analytics: "YOUR_GOOGLE_ANALYTICS_CODE_HERE"
date_columns: ""

# Build settings
markdown: kramdown
